### ISSUE TITLE
Does Caffe2 get special operator for depth-wise convolution?

### ISSUE THREAD

**Issue by lhCheung1991** [camel007/caffe2-mobilenet#2]
Hi, 

Does Caffe2 get special operator for depth-wise convolution? I don't see it in your source.

Could you pls figure it out for me?

**Comment by camel007** [comment]
[brew.group_conv](https://github.com/caffe2/caffe2/blob/f0ea8046c26d9c324dc34deb2bfd8e3738e9f02c/caffe2/python/brew.py#L57)

**Comment by lhCheung1991** [comment]
I didn’t find the document of group_conv operator, could you pls show me 
the link.

Thank you very much

From:  张垚 <notifications@github.com>
Reply-To:  camel007/caffe2-mobilenet 
<reply+0083394d6fa9ffc1036f3bd7a18f076be2055fc05a5b756b92cf0000000115a3965f
92a169ce0edabb6a@reply.github.com>
Date:  Thursday, August 10, 2017 at 11:34
To:  camel007/caffe2-mobilenet <caffe2-mobilenet@noreply.github.com>
Cc:  Linghan Zhang <lhcheung1991@gmail.com>, Author 
<author@noreply.github.com>
Subject:  Re: [camel007/caffe2-mobilenet] Does Caffe2 get special operator 
for depth-wise convolution? (#2)


brew.group_conv

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4
bb","name":"GitHub"},"entity":{"external_key":"github/camel007/caffe2-mobil
enet","title":"camel007/caffe2-mobilenet","subtitle":"GitHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/14
3418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":
"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-1
1e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/camel007/caffe2-mobilenet"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@camel007 in #2: 
[brew.group_conv](https://github.com/caffe2/caffe2/blob/f0ea8046c26d9c324dc
34deb2bfd8e3738e9f02c/caffe2/python/brew.py#L57)"}],"action":{"name":"View 
Issue","url":"https://github.com/camel007/caffe2-mobilenet/issues/2#issueco
mment-321441463"}}}

**Comment by lhCheung1991** [comment]
Solved it. Thanks

**Comment by camel007** [comment]
Please read the source code发自我的iPhone------------------ Original ------------------From: Linghan Cheung  <notifications@github.com>Date: 周四,8月 10,2017 11:46To: camel007/caffe2-mobilenet <caffe2-mobilenet@noreply.github.com>Cc: 张垚 <yaozhang.chn@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [camel007/caffe2-mobilenet] Does Caffe2 get special operator fordepth-wise convolution? (#2)I didn’t find the document of group_conv operator, could you pls show me 
the link.

Thank you very much

From:  张垚 <notifications@github.com>
Reply-To:  camel007/caffe2-mobilenet 
<reply+0083394d6fa9ffc1036f3bd7a18f076be2055fc05a5b756b92cf0000000115a3965f
92a169ce0edabb6a@reply.github.com>
Date:  Thursday, August 10, 2017 at 11:34
To:  camel007/caffe2-mobilenet <caffe2-mobilenet@noreply.github.com>
Cc:  Linghan Zhang <lhcheung1991@gmail.com>, Author 
<author@noreply.github.com>
Subject:  Re: [camel007/caffe2-mobilenet] Does Caffe2 get special operator 
for depth-wise convolution? (#2)


brew.group_conv

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4
bb","name":"GitHub"},"entity":{"external_key":"github/camel007/caffe2-mobil
enet","title":"camel007/caffe2-mobilenet","subtitle":"GitHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/14
3418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":
"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-1
1e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/camel007/caffe2-mobilenet"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@camel007 in #2: 
[brew.group_conv](https://github.com/caffe2/caffe2/blob/f0ea8046c26d9c324dc
34deb2bfd8e3738e9f02c/caffe2/python/brew.py#L57)"}],"action":{"name":"View 
Issue","url":"https://github.com/camel007/caffe2-mobilenet/issues/2#issueco
mment-321441463"}}}


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/camel007/caffe2-mobilenet","title":"camel007/caffe2-mobilenet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/camel007/caffe2-mobilenet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lhCheung1991 in #2: I didn’t find the document of group_conv operator, could you pls show me \nthe link.\n\nThank you very much\n\nFrom:  张垚 \u003cnotifications@github.com\u003e\nReply-To:  camel007/caffe2-mobilenet \n\u003creply+0083394d6fa9ffc1036f3bd7a18f076be2055fc05a5b756b92cf0000000115a3965f\n92a169ce0edabb6a@reply.github.com\u003e\nDate:  Thursday, August 10, 2017 at 11:34\nTo:  camel007/caffe2-mobilenet \u003ccaffe2-mobilenet@noreply.github.com\u003e\nCc:  Linghan Zhang \u003clhcheung1991@gmail.com\u003e, Author \n\u003cauthor@noreply.github.com\u003e\nSubject:  Re: [camel007/caffe2-mobilenet] Does Caffe2 get special operator \nfor depth-wise convolution? (#2)\n\n\nbrew.group_conv\n\n—\nYou are receiving this because you authored the thread.\nReply to this email directly, view it on GitHub, or mute the thread.\n\n  \n{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4\nbb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/camel007/caffe2-mobil\nenet\",\"title\":\"camel007/caffe2-mobilenet\",\"subtitle\":\"GitHub \nrepository\",\"main_image_url\":\"https://cloud.githubusercontent.com/assets/14\n3418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png\",\"avatar_image_url\":\n\"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-1\n1e6-9aed-b52498112777.png\",\"action\":{\"name\":\"Open in \nGitHub\",\"url\":\"https://github.com/camel007/caffe2-mobilenet\"}},\"updates\":{\"\nsnippets\":[{\"icon\":\"PERSON\",\"message\":\"@camel007 in #2: \n[brew.group_conv](https://github.com/caffe2/caffe2/blob/f0ea8046c26d9c324dc\n34deb2bfd8e3738e9f02c/caffe2/python/brew.py#L57)\"}],\"action\":{\"name\":\"View \nIssue\",\"url\":\"https://github.com/camel007/caffe2-mobilenet/issues/2#issueco\nmment-321441463\"}}}\n"}],"action":{"name":"View Issue","url":"https://github.com/camel007/caffe2-mobilenet/issues/2#issuecomment-321442716"}}}
